import * as gtfsModule from "https://cdn.jsdelivr.net/npm/gtfs-realtime-bindings@1.1.1/+esm";
import JSZip from "https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm";

const gtfsRoot = gtfsModule.default || gtfsModule;
const transitRealtime =
  gtfsRoot.transit_realtime ||
  gtfsRoot.default?.transit_realtime ||
  gtfsRoot;

const ROUTES={"1":"#EE352E","2":"#EE352E","3":"#EE352E","4":"#00933C","5":"#00933C","6":"#00933C","7":"#B933AD","A":"#0039A6","C":"#0039A6","E":"#0039A6","B":"#FF6319","D":"#FF6319","F":"#FF6319","M":"#FF6319","G":"#6CBE45","J":"#996633","Z":"#996633","L":"#A7A9AC","N":"#FCCC0A","Q":"#FCCC0A","R":"#FCCC0A","W":"#FCCC0A","S":"#808183","SI":"#0039A6"};
const FEEDS=["gtfs","gtfs-ace","gtfs-bdfm","gtfs-g","gtfs-jz","gtfs-l","gtfs-nqrw","gtfs-si"];
const STATIC_URL="https://rrgtfsfeeds.s3.amazonaws.com/gtfs_subway.zip";
const VIEWS={system:[[40.56,-74.06],[40.91,-73.70]],manhattan:[[40.69,-74.03],[40.89,-73.91]],brooklyn:[[40.56,-74.05],[40.74,-73.83]],queens:[[40.60,-73.97],[40.82,-73.70]],bronx:[[40.78,-73.95],[40.92,-73.76]]};
const $=id=>document.getElementById(id);
let settings=readSettings(),map,stations={},stationLayers=[],trainLayers=[],trips=[],selectedRoute="ALL",selectedTrip=null,lastUpdate=null,demoPhase=0;

function readSettings(){try{return JSON.parse(localStorage.getItem("signal-board-v3")||'{"worker":"","focus":"system"}')}catch(_){return{worker:"",focus:"system"}}}
function clock(){const d=new Date();$("clock").textContent=d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});$("date").textContent=d.toLocaleDateString([],{weekday:"short",month:"short",day:"numeric"}).toUpperCase();if(lastUpdate)$("feedAge").textContent=Math.max(0,Math.round((Date.now()-lastUpdate)/1000))+" SEC"}
setInterval(clock,1000);clock();

function color(r){return ROUTES[r]||"#b68b44"}function textColor(r){return ["N","Q","R","W"].includes(r)?"#111":"#fff"}function normalizeRoute(r){return String(r||"?").replace(/X$/,"")}
function initializeMap(){map=L.map("map",{zoomControl:false,minZoom:9,maxZoom:15});L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}{r}.png",{attribution:"© OpenStreetMap © CARTO",subdomains:"abcd",maxZoom:20}).addTo(map);focusMap()}
function focusMap(){map.fitBounds(VIEWS[settings.focus]||VIEWS.system,{padding:[8,8]})}
function filters(){const list=["ALL",...Object.keys(ROUTES)];$("routeFilters").innerHTML=list.map(r=>`<button class="filter ${r==="ALL"?"active":""}" data-route="${r}" style="background:${r==="ALL"?"#675d48":color(r)};color:${r==="ALL"?"#fff":textColor(r)}">${r==="ALL"?"•":r}</button>`).join("");$("routeFilters").addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;selectedRoute=b.dataset.route;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));selectedTrip=null;render()})}
function services(){$("serviceList").innerHTML=Object.keys(ROUTES).map(r=>`<div class="service"><span class="mini" style="background:${color(r)};color:${textColor(r)}">${r}</span><span>GOOD SERVICE</span><em></em></div>`).join("")}

function parseCSV(text){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c=='"'&&quoted&&n=='"'){field+='"';i++}else if(c=='"')quoted=!quoted;else if(c==","&&!quoted){row.push(field);field=""}else if((c=="\n"||c=="\r")&&!quoted){if(c=="\r"&&n=="\n")i++;row.push(field);if(row.some(v=>v))rows.push(row);row=[];field=""}else field+=c}if(field||row.length){row.push(field);rows.push(row)}const headers=rows.shift()||[];return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||""])))}
async function loadStations(){try{const response=await fetch(STATIC_URL);if(!response.ok)throw Error("HTTP "+response.status);const zip=await JSZip.loadAsync(await response.arrayBuffer());const stops=parseCSV(await zip.file("stops.txt").async("string"));stops.filter(s=>s.location_type==="1"||(!s.parent_station&&!/[NS]$/.test(s.stop_id))).forEach(s=>stations[s.stop_id]={id:s.stop_id,name:s.stop_name,lat:+s.stop_lat,lon:+s.stop_lon});drawStations();$("noticeText").textContent="Official MTA station diagram loaded. Establishing realtime telegraph…"}catch(error){console.error(error);installFallbackStations();$("noticeText").textContent="Official station file unavailable; reduced system diagram loaded."}}
function installFallbackStations(){[["A24","59 St–Columbus Circle",40.7683,-73.9819],["A27","42 St–Port Authority",40.7573,-73.9897],["A32","W 4 St",40.7323,-74.0005],["A42","Fulton St",40.7102,-74.0078],["R16","Times Sq–42 St",40.7555,-73.9877],["R20","14 St–Union Sq",40.7357,-73.9906],["635","Grand Central–42 St",40.7518,-73.9767],["631","14 St–Union Sq",40.7347,-73.9901]].forEach(d=>stations[d[0]]={id:d[0],name:d[1],lat:d[2],lon:d[3]});drawStations()}
function drawStations(){stationLayers.forEach(x=>x.remove());stationLayers=[];Object.values(stations).forEach(s=>{const icon=L.divIcon({className:"",html:'<div class="station-dot"></div>',iconSize:[6,6],iconAnchor:[3,3]});stationLayers.push(L.marker([s.lat,s.lon],{icon,interactive:false}).addTo(map))})}
function station(id){return stations[String(id||"").replace(/[NS]$/,"")]}

function decode(message){if(!transitRealtime?.FeedMessage?.decode)throw Error("GTFS decoder unavailable");return transitRealtime.FeedMessage.decode(message)}
async function fetchFeed(name){const response=await fetch(settings.worker.replace(/\/$/,"")+"/feed?name="+encodeURIComponent(name),{cache:"no-store"});if(!response.ok)throw Error(name+" HTTP "+response.status);return decode(new Uint8Array(await response.arrayBuffer()))}
function deriveTrips(messages){const now=Math.floor(Date.now()/1000),result=[];for(const message of messages){for(const entity of message.entity||[]){const update=entity.tripUpdate;if(!update?.trip)continue;const times=update.stopTimeUpdate||[];if(!times.length)continue;let index=times.findIndex(x=>Number(x.arrival?.time||x.departure?.time||0)>=now-45);if(index<0)index=times.length-1;const next=times[index],previous=times[Math.max(0,index-1)],a=station(previous?.stopId),b=station(next?.stopId);if(!a&&!b)continue;let lat=(b||a).lat,lon=(b||a).lon,progress=.1;const at=Number(next?.arrival?.time||next?.departure?.time||0),pt=Number(previous?.departure?.time||previous?.arrival?.time||0);if(a&&b&&at>pt){progress=Math.max(0,Math.min(1,(now-pt)/(at-pt)));lat=a.lat+(b.lat-a.lat)*progress;lon=a.lon+(b.lon-a.lon)*progress}result.push({id:update.trip.tripId||entity.id,route:normalizeRoute(update.trip.routeId),direction:update.trip.directionId===1?"Southbound / Downtown":"Northbound / Uptown",from:a?.name||b?.name||"Unknown",to:b?.name||"Unknown",eta:at?Math.max(0,Math.round((at-now)/60)):null,lat,lon})}}return result}
async function loadLive(){if(!settings.worker){demo();return}setConnection("loading","CONNECTING");try{const settled=await Promise.allSettled(FEEDS.map(fetchFeed)),messages=settled.filter(x=>x.status==="fulfilled").map(x=>x.value);if(!messages.length)throw Error("All MTA feed requests failed");trips=deriveTrips(messages);lastUpdate=Date.now();setConnection("live","LIVE TELEGRAPH");$("mode").textContent="LIVE";$("noticeText").textContent="Realtime MTA trip updates received. Lamps indicate estimated positions between reported stations.";render()}catch(error){console.error(error);setConnection("error","LIVE FEED ERROR");$("noticeText").textContent="Live telegraph failed: "+error.message+". Demonstration movement is shown while the board retries.";demo(false)}}
function setConnection(state,label){$("connection").className="connection "+state;$("connection").querySelector("span").textContent=label}
function demo(reset=true){const ids=Object.keys(stations);if(!ids.length)return;if(reset)demoPhase+=.17;const routes=Object.keys(ROUTES).slice(0,18);trips=routes.map((route,i)=>{const a=stations[ids[(i*5)%ids.length]],b=stations[ids[(i*5+1)%ids.length]]||a,p=(Math.sin(demoPhase+i*.75)+1)/2;return{id:"demo-"+i,route,direction:i%2?"Southbound / Downtown":"Northbound / Uptown",from:a.name,to:b.name,eta:Math.max(1,Math.round((1-p)*6)),lat:a.lat+(b.lat-a.lat)*p,lon:a.lon+(b.lon-a.lon)*p}});setConnection("demo","DEMONSTRATION");$("mode").textContent="DEMO";render()}

function choose(t){selectedTrip=t;$("tripBullet").textContent=t.route;$("tripBullet").style.background=color(t.route);$("tripBullet").style.color=textColor(t.route);$("tripTitle").textContent=t.route+" TRAIN";$("tripDirection").textContent=t.direction;$("fromStation").textContent=t.from;$("toStation").textContent=t.to;$("eta").textContent=t.eta==null?"—":t.eta+" MIN";render(false)}
function render(auto=true){trainLayers.forEach(x=>x.remove());trainLayers=[];const shown=trips.filter(t=>selectedRoute==="ALL"||t.route===selectedRoute);shown.slice(0,250).forEach(t=>{const selected=selectedTrip?.id===t.id,icon=L.divIcon({className:"",html:`<div class="train-dot ${selected?"selected":""}" style="background:${color(t.route)};color:${color(t.route)}"></div>`,iconSize:[18,18],iconAnchor:[9,9]});trainLayers.push(L.marker([t.lat,t.lon],{icon,zIndexOffset:selected?1000:100}).addTo(map).on("click",()=>choose(t)))});$("trainCount").textContent=shown.length;$("lineCount").textContent=new Set(shown.map(t=>t.route)).size;$("updated").textContent="UPDATED "+new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit",second:"2-digit"});if(auto&&shown.length&&!selectedTrip)choose(shown[0])}

window.addEventListener("signal-settings-changed",event=>{settings=event.detail;focusMap();selectedTrip=null;loadLive()});
initializeMap();filters();services();await loadStations();await loadLive();
setInterval(()=>settings.worker?loadLive():(demoPhase+=.22,demo()),15000);
